version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: antelope
    env_file:
      - stack.env
    ports:
      - "3004:3004"
    restart: unless-stopped